# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdockerkrish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://testdockerkrish.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_63114c12d7834e11a9b1d54105c9cfab }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d362748f78c34682833ade23e93ef0e9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: testdockerkrish.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_63114c12d7834e11a9b1d54105c9cfab }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdockerkrish'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_27c6839d40c148829f4ba2baf4887e21 }}
        images: 'testdockerkrish.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_63114c12d7834e11a9b1d54105c9cfab }}/studentperformance:${{ github.sha }}'